# Header
menu:
  Home: /
  Archives: /archives
  About: /About

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: left
widgets:
- category
- tag
- archive
- recent_posts

# Miscellaneous
google_analytics:
favicon: /img/favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id: